# Generated by Django 4.0.10 on 2023-07-04 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='General',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('basic_access', 'Basic access to this app'),),
                'managed': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=500)),
                ('name', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=255)),
                ('thumbnail', models.CharField(max_length=255)),
            ],
            options={
                'permissions': (('manage_links', 'Can manage links'),),
                'default_permissions': (),
            },
        ),
    ]
