# Generated by Django 4.0.10 on 2023-07-05 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asmek_authcogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
