# Generated by Django 4.0.10 on 2023-07-31 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asmek_authcogs', '0002_alter_link_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='general',
            options={'default_permissions': (), 'managed': False, 'permissions': (('basic_access', 'Basic access to this app'), ('siege_control', 'Control siege colours'))},
        ),
    ]
