# Generated by Django 4.0.10 on 2023-08-02 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("asmek_authcogs", "0003_alter_general_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuthCogs",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "permissions": (
                    ("basic_access", "Basic access to this app"),
                    ("siege_control", "Control siege colours"),
                ),
                "managed": False,
                "default_permissions": (),
            },
        ),
        migrations.DeleteModel(
            name="General",
        ),
    ]
