# Generated by Django 4.0.10 on 2024-01-05 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("asmek_authcogs", "0005_groupwelcome"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="groupwelcome",
            name="thumbnail",
        ),
    ]
